import { ArrowUpRight, BrainCircuit, ChevronRight, CircleAlert, Leaf, ShieldCheck, Trophy, TrendingDown, TrendingUp } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { formatCarbon } from '../pages';
import type { DashboardModel } from '../data/dashboard';
import { generateInsight, type GeneratedInsight } from '../data/insights';
import type { Route } from '../types';
import { Badge, Button, Card } from './ui';

export function Dashboard({ dashboard, onNavigate }: { dashboard: DashboardModel; onNavigate: (route: Route) => void }) {
  const [showInsights, setShowInsights] = useState(true);
  const [generatedInsight, setGeneratedInsight] = useState<GeneratedInsight>();
  const [insightError, setInsightError] = useState<string>();
  const [generating, setGenerating] = useState(false);
  const goal = dashboard.carbonGoals[0];
  const alert = dashboard.governanceAlerts[0];
  const insights = [
    { priority: 'Critical', title: 'Recover the carbon target', text: goal ? `${goal.title} is ${formatCarbon(goal.varianceTonnes)} above plan.` : 'No carbon goals are configured.', route: 'environmental' as const, action: 'Review carbon ledger' },
    { priority: 'High', title: 'Close governance gaps', text: alert ? `${alert.title} is assigned to ${alert.ownerName} and due ${alert.dueDate}.` : 'No open governance alerts need attention.', route: 'governance' as const, action: 'Review governance' },
    { priority: 'Opportunity', title: 'Verify participation', text: `${dashboard.participation.awaitingReview} submission(s) await review at ${dashboard.participation.averageProgress}% average progress.`, route: 'challenges' as const, action: 'Review challenge evidence' },
  ];
  const createInsight = async () => { setGenerating(true); setInsightError(undefined); try { setGeneratedInsight(await generateInsight()); } catch (error) { setInsightError(error instanceof Error ? error.message : 'Unable to generate an insight.'); } finally { setGenerating(false); } };
  return <>
    <section className="page-intro"><div><p className="eyebrow">{dashboard.asOfDate} · COMMAND CENTER</p><h1>Sustainability, made actionable.</h1><p>Measure the operational signals that matter, then turn them into accountable next steps.</p></div><Button onClick={() => setShowInsights(!showInsights)}><BrainCircuit size={16} /> {showInsights ? 'Hide' : 'Show'} insights</Button></section>
    <section className="welcome"><div><span className="live-dot" /> Live ESG position</div><p>Trusted scores are calculated in EcoSphere’s data layer.</p><ChevronRight size={17} /></section>
    <section className="metric-grid"><Metric label="ESG score" value={`${dashboard.scores.esg}`} sub="E 40% · S 30% · G 30%" /><Metric label="Carbon footprint" value={formatCarbon(dashboard.carbonFootprintTonnes)} sub="Recorded operational activity" /><Metric label="Active risks" value={`${dashboard.governance.activeRisks}`} sub="Governance signals" /><Metric label="Participation" value={`${dashboard.participation.averageProgress}%`} sub="Active challenge progress" /></section>
    {showInsights && <section className="ai-actions"><div className="ai-actions-heading"><div><p className="eyebrow">ECOSPHERE INSIGHT ENGINE · GROUNDED RECOMMENDATIONS</p><h2>What needs attention next</h2></div><span><BrainCircuit size={16} /> Based only on trusted metrics</span></div><div className="form-actions"><Button variant="secondary" disabled={generating} onClick={() => void createInsight()}><BrainCircuit size={15} />{generating ? 'Generating…' : 'Generate AI insight'}</Button>{insightError && <p className="sign-in-error">{insightError}</p>}</div><div className="insight-grid">{generatedInsight && <Card className="action-card"><div className="section-label"><Badge tone={generatedInsight.priority === 'Critical' ? 'red' : generatedInsight.priority === 'High' ? 'amber' : 'green'}>{generatedInsight.priority}</Badge><span>Gemini · source metrics saved</span></div><h3>{generatedInsight.title}</h3><p>{generatedInsight.recommendation}</p><small>{generatedInsight.rationale}</small><Button variant="secondary" onClick={() => onNavigate(generatedInsight.route)}>Open workflow <ArrowUpRight size={15} /></Button></Card>}{insights.map((insight) => <Card className="action-card" key={insight.title}><div className="section-label"><Badge tone={insight.priority === 'Critical' ? 'red' : insight.priority === 'High' ? 'amber' : 'green'}>{insight.priority}</Badge><span>Grounded recommendation</span></div><h3>{insight.title}</h3><p>{insight.text}</p><Button variant="secondary" onClick={() => onNavigate(insight.route)}>{insight.action}<ArrowUpRight size={15} /></Button></Card>)}</div></section>}
    <section className="pillar-grid"><Pillar title="Environmental" score={dashboard.scores.environmental} icon={<Leaf size={16} />} tone="green" /><Pillar title="Social" score={dashboard.scores.social} icon={<Trophy size={16} />} tone="amber" /><Pillar title="Governance" score={dashboard.scores.governance} icon={<ShieldCheck size={16} />} tone="red" /></section>
    <section className="command-grid"><Card className="trend-card"><div className="section-label">CARBON POSITION <Badge tone={goal?.varianceTonnes ? 'amber' : 'green'}><TrendingUp size={11} /> {goal?.varianceTonnes ? 'Above plan' : 'On plan'}</Badge></div><div className="trend-value"><strong>{formatCarbon(dashboard.carbonFootprintTonnes)}</strong><span>Recorded to date</span></div><div className="trend-bars" aria-label="Carbon position"><i className="current" style={{ height: `${Math.min(goal?.percentageUsed ?? 0, 100)}%` }} /></div></Card><Card className="ranking-card"><div className="section-label">DEPARTMENT RANKING <span>Carbon vs. target</span></div>{dashboard.departmentRanking.map((department, index) => <div className="rank-row" key={department.departmentId}><b>0{index + 1}</b><div><strong>{department.name}</strong><div className="progress"><i style={{ width: `${Math.min(department.percentageUsed, 100)}%` }} /></div></div><span className={department.percentageUsed > 100 ? 'over' : ''}>{department.percentageUsed}%</span></div>)}</Card>{goal && <Card className="goal-card"><div className="section-label">GOAL PROGRESS <Badge tone={goal.varianceTonnes > 0 ? 'red' : 'green'}>{goal.status.replace('-', ' ')}</Badge></div><h2>{goal.title}</h2><p><strong>{formatCarbon(goal.actualTonnes)}</strong> recorded against a {goal.targetTonnes} tCO₂e target.</p><div className="goal-progress"><i style={{ width: `${Math.min(goal.percentageUsed, 100)}%` }} /></div><span>{goal.targetDate} target date</span></Card>}{alert && <Card className="alert-card"><div><CircleAlert size={19} /><Badge tone="red">Governance alert</Badge></div><h2>{alert.title}</h2><p>Owned by {alert.ownerName} · due {alert.dueDate}. Resolve the evidence gap before reporting.</p><Button variant="secondary" onClick={() => onNavigate('governance')}>Review risk <ArrowUpRight size={15} /></Button></Card>}</section>
  </>;
}
function Pillar({ title, score, icon, tone }: { title: string; score: number; icon: ReactNode; tone: 'green' | 'amber' | 'red' }) { return <Card className="pillar-card"><span className={`pillar-icon ${tone}`}>{icon}</span><div><p>{title}</p><strong>{score}</strong><small>out of 100</small></div><TrendingDown size={17} /></Card>; }
function Metric({ label, value, sub }: { label: string; value: string; sub: string }) { return <Card className="metric"><p>{label}</p><strong>{value}</strong><small>{sub}</small></Card>; }
