import { BarChart3, Bell, Check, ChevronDown, FileText, Gauge, Leaf, Menu, Settings, ShieldCheck, Sparkles, Trophy, X } from 'lucide-react';
import { useState } from 'react';
import type { DemoUser, EcoSphereDatabase, NavItem, Route } from '../types';

const navigation: NavItem[] = [
  { id: 'dashboard', label: 'Command Center', icon: Gauge }, { id: 'environmental', label: 'Environmental', icon: Leaf }, { id: 'governance', label: 'Governance', icon: ShieldCheck },
  { id: 'challenges', label: 'Challenges', icon: Trophy }, { id: 'reports', label: 'Reports', icon: FileText }, { id: 'settings', label: 'Settings', icon: Settings },
];
export function AppShell({ route, onNavigate, user, database, onSignOut, children }: { route: Route; onNavigate: (route: Route) => void; user: DemoUser; database: EcoSphereDatabase; onSignOut: () => void; children: React.ReactNode }) {
  const [mobileOpen, setMobileOpen] = useState(false); const [notificationsOpen, setNotificationsOpen] = useState(false); const [seen, setSeen] = useState(false);
  const visibleNavigation = navigation.filter((item) => user.role !== 'employee' || ['dashboard', 'challenges', 'settings'].includes(item.id));
  const challenge=database.challenges.find(item=>item.status==='active'); const participation=challenge&&database.participations.find(item=>item.challengeId===challenge.id&&item.userId===user.id); const issue=database.complianceIssues.find(item=>item.severity==='high'&&item.status!=='resolved'); const pendingPolicy=!database.policyAcknowledgements.some(item=>item.userId===user.id&&item.status==='acknowledged'); const notifications=[participation?.status==='approved'&&{title:'Participation approved',detail:`${challenge?.pointReward} EcoPoints were added to your balance.`,route:'challenges' as Route,tone:'success'},participation?.status==='approved'&&database.badges.some(item=>item.userId===user.id)&&{title:'Badge unlocked',detail:'Your verified action earned a recognition badge.',route:'challenges' as Route,tone:'success'},pendingPolicy&&{title:'Policy reminder',detail:'Your Sustainability Code acknowledgement is pending.',route:'governance' as Route,tone:'reminder'},user.role!=='employee'&&issue&&{title:'Overdue compliance issue',detail:`${issue.title} needs owner action.`,route:'governance' as Route,tone:'risk'}].filter(Boolean) as {title:string;detail:string;route:Route;tone:string}[];
  return <div className="app-shell"><aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><div className="brand"><span className="brand-mark"><Sparkles size={17} /></span><span>EcoSphere</span><button className="mobile-close" onClick={() => setMobileOpen(false)}><X size={18}/></button></div><div className="workspace"><span>WORKSPACE</span><button>Atlas Industries <ChevronDown size={14}/></button></div><nav>{visibleNavigation.map(({ id, label, icon: Icon }) => <button key={id} className={route === id ? 'active' : ''} onClick={() => { onNavigate(id); setMobileOpen(false); }}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="security"><ShieldCheck size={17}/><span><b>Enterprise-ready</b><small>Governed sustainability</small></span></div><button className="profile" onClick={onSignOut} title="Switch demo persona"><span className="avatar">{user.initials}</span><span><b>{user.name}</b><small>{user.title}</small></span><ChevronDown size={14}/></button></div></aside><div className="shell-main"><header className="topbar"><button className="menu-button" onClick={() => setMobileOpen(true)}><Menu size={20}/></button><div className="crumb"><span>Atlas Industries</span><span>/</span><strong>{navigation.find(n => n.id === route)?.label}</strong></div><div className="filters"><button className="filter"><BarChart3 size={15}/><span>{user.role === 'employee' ? 'My department' : 'All departments'}</span><ChevronDown size={14}/></button><button className="filter"><span className="calendar-dot"/>Jul 1 – Jul 31, 2026<ChevronDown size={14}/></button><button className="notification-button" aria-label="Notifications" onClick={()=>{setNotificationsOpen(!notificationsOpen);setSeen(true)}}><Bell size={17}/>{notifications.length>0&&!seen&&<i/>}</button></div></header>{notificationsOpen&&<div className="notification-panel"><div><span className="section-label">NOTIFICATIONS</span><button onClick={()=>setNotificationsOpen(false)}><X size={16}/></button></div>{notifications.length?notifications.map(item=><button key={item.title} className={`notification-item ${item.tone}`} onClick={()=>{onNavigate(item.route);setNotificationsOpen(false)}}><span>{item.tone==='success'?<Check size={14}/>:<Bell size={14}/>}</span><p><b>{item.title}</b><small>{item.detail}</small></p></button>):<p className="notification-empty">You’re all caught up.</p>}</div>}<main>{children}</main></div></div>;
}
