import { ArrowUpRight, ChevronRight, CircleAlert, FileText, Leaf, Plus, ShieldCheck, Sparkles, Trophy } from 'lucide-react';
import { Badge, Button, Card, EmptyState } from './components/ui';
import type { Route } from './types';

const pageInfo: Record<Exclude<Route, 'dashboard'>, { eyebrow: string; title: string; description: string; icon: typeof Leaf; action: string }> = {
  environmental: { eyebrow: 'Environmental pillar', title: 'Environmental performance', description: 'Measure operational impact, trace emissions, and steer your carbon plan.', icon: Leaf, action: 'Add activity' },
  governance: { eyebrow: 'Governance pillar', title: 'Governance and compliance', description: 'Bring ownership, policy compliance, and material risks into one accountable view.', icon: ShieldCheck, action: 'Create issue' },
  challenges: { eyebrow: 'Social pillar', title: 'Employee challenges', description: 'Turn sustainability goals into visible participation and recognition.', icon: Trophy, action: 'Create challenge' },
  reports: { eyebrow: 'Executive reporting', title: 'ESG reports', description: 'Prepare a clear, trusted view of impact for every stakeholder.', icon: FileText, action: 'Create report' },
  settings: { eyebrow: 'Workspace', title: 'Settings', description: 'Configure your organization, departments, and future data connections.', icon: Sparkles, action: 'Manage workspace' },
};
export function Dashboard() { return <><section className="page-intro"><div><p className="eyebrow">JULY 2026 · EXECUTIVE OVERVIEW</p><h1>Sustainability, made actionable.</h1><p>One trusted workspace for environmental impact, governance accountability, and employee momentum.</p></div><Button><Sparkles size={16}/> Ask EcoSphere AI</Button></section><section className="welcome"><div><span className="live-dot"/> Foundation preview</div><p>Your connected ESG command center is ready for operational data.</p><ChevronRight size={17}/></section><section className="metric-grid"><Metric label="ESG score" value="—" sub="Calculated when data is connected"/><Metric label="Carbon footprint" value="—" sub="CO₂e this period"/><Metric label="Active risks" value="—" sub="Governance signals"/><Metric label="Participation" value="—" sub="Employee momentum"/></section><section className="dashboard-grid"><Card className="score-card"><div className="section-label">ESG POSITION <Badge tone="neutral">Awaiting data</Badge></div><div className="score-empty"><div className="score-ring"><Sparkles size={25}/></div><div><h2>Your impact story starts here.</h2><p>Environmental, Social, and Governance signals will converge into one decision-ready score.</p></div></div></Card><Card className="insight-card"><div className="section-label">ECOSPHERE INTELLIGENCE <span className="ai-chip"><Sparkles size={13}/> AI</span></div><h2>Built to turn signals into next steps.</h2><p>Once your operational and governance records are connected, EcoSphere will surface the decision that matters most.</p><Button variant="secondary">See how intelligence works <ArrowUpRight size={15}/></Button></Card><Card className="activity-card"><div className="section-label">ACTIVITY <span>Coming in Phase 2</span></div><EmptyState title="Your workspace is quiet" detail="Data, people, and decisions will appear here as your ESG story takes shape." /></Card></section></> }
function Metric({ label, value, sub }: { label: string; value: string; sub: string }) { return <Card className="metric"><p>{label}</p><strong>{value}</strong><small>{sub}</small></Card>; }
export function PlaceholderPage({ route }: { route: Exclude<Route, 'dashboard'> }) { const info = pageInfo[route]; const Icon = info.icon; return <><section className="page-intro"><div><p className="eyebrow">{info.eyebrow}</p><h1>{info.title}</h1><p>{info.description}</p></div><Button><Plus size={16}/>{info.action}</Button></section><Card className="route-hero"><div className="route-icon"><Icon size={26}/></div><div><Badge tone="green">Foundation complete</Badge><h2>Ready for the next layer.</h2><p>This route is intentionally data-light in Phase 1. Its shared foundation, navigation, and visual system are ready for the scoped workflow in the next roadmap phases.</p></div></Card><Card className="table-card"><div className="table-head"><div><h2>{route === 'settings' ? 'Workspace configuration' : 'Records'}</h2><p>Structured data will appear here once connected.</p></div><Button variant="secondary">View guide</Button></div><div className="table-placeholder"><span>STATUS</span><span>OWNER</span><span>UPDATED</span></div></Card></> }
